default:
	musl-gcc prnt16.c -o prnt16 -Os -Wall -s -static
	musl-gcc strn64.c -o strn64 -Os -Wall -s -static
	musl-gcc strsum.c -o strsum -Os -Wall -s -static
	musl-gcc mixtrd.c -o mixtrd -Os -Wall -s -static -lpthread
	musl-gcc uchaos.c -o uchaos -Os -Wall -s -static -lm --fast-math
